In [15]:
import pandas as pd

path = r'/home/iagojorcovix/projeto_medcare_curitiba/data_raw/2025-06-06_Sistema_E-Saude_Medicos_-_Base_de_Dados.csv'

df = pd.read_csv(
    path,
    encoding='latin1',
    sep=';'
)

df.head()

/tmp/ipykernel_7076/2925851600.py:5: DtypeWarning: Columns (0: Código do CBO) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(

,Data do Atendimento,Data de Nascimento,Sexo,Código do Tipo de Unidade,Tipo de Unidade,Código da Unidade,Descrição da Unidade,Código do Procedimento,Descrição do Procedimento,Código do CBO,...,Grupo Comunitário,Meio de Comunicacao,Meio de Transporte,Municício,Bairro,Nacionalidade,cod_usuario,origem_usuario,residente,cod_profissional
0,01/02/2025 00:10:45,06/10/1993 00:00:00,M,2,UPA,9214097,UPA TATUQUARA,301060096,ATENDIMENTO MEDICO EM UNIDADE DE PRONTO ATENDI...,225125,...,NAO PARTICIPA,"TELEVISAO,RADIO","ONIBUS,CARRO",CURITIBA,TATUQUARA,Estrangeiro,12099862,1,1,128347
1,01/02/2025 00:20:05,19/12/1997 00:00:00,F,2,UPA,3827836,UPA PINHEIRINHO,301060096,ATENDIMENTO MEDICO EM UNIDADE DE PRONTO ATENDI...,225125,...,NAO PARTICIPA,"TELEVISAO,RADIO,OUTROS","OUTROS,ONIBUS,CARRO",CURITIBA,PINHEIRINHO,Brasileira,182635,1,1,127612
2,01/02/2025 00:25:08,06/10/1990 00:00:00,F,2,UPA,5323436,UPA CAJURU,301060096,ATENDIMENTO MEDICO EM UNIDADE DE PRONTO ATENDI...,225125,...,NAO PARTICIPA,RADIO,ONIBUS,CURITIBA,CAJURU,Brasileira,2484209,1,1,116606
3,01/02/2025 00:11:35,13/10/1976 00:00:00,M,2,UPA,9214097,UPA TATUQUARA,301060096,ATENDIMENTO MEDICO EM UNIDADE DE PRONTO ATENDI...,225125,...,OUTROS,"TELEVISAO,RADIO,OUTROS","ONIBUS,CARRO",CURITIBA,CAMPO DE SANTANA,Brasileira,3536128,1,1,97106
4,01/02/2025 00:29:48,03/09/2001 00:00:00,F,2,UPA,5323495,UPA CIDADE INDUSTRIAL,301060096,ATENDIMENTO MEDICO EM UNIDADE DE PRONTO ATENDI...,225125,...,NAO PARTICIPA,"TELEVISAO,RADIO,OUTROS","ONIBUS,CARRO",CURITIBA,NOVO MUNDO,Brasileira,9886667,1,1,115423

In [7]:
df.shape

(1218394, 42)

In [14]:
nulls = pd.DataFrame({
    'qtd_null': df.isna().sum(),
    'pct_null': df.isna().mean() * 100
})

nulls.sort_values('pct_null', ascending=False)

                                              qtd_null   pct_null
Data do Internamento                           1213946  99.634929
Estabelecimento Destino                        1213625  99.608583
CID do Internamento                            1213625  99.608583
Estabelecimento Solicitante                    1213625  99.608583
Área de Atuação                                1093136  89.719418
Grupo Comunitário                               248626  20.406043
Fezes/Urina                                     245805  20.174508
Meio de Comunicacao                             244382  20.057715
Meio de Transporte                              243993  20.025788
Abastecimento                                   243930  20.020617
Destino Lixo                                    243562  19.990414
Em Caso de Doença                               242656  19.916053
Tipo de Habitação                               241814  19.846946
Tratamento no Domicílio                         240684  19.754201
Cômodos                                          54236   4.451434
Código do CID                                      299   0.024541
Descrição do CID                                   299   0.024541
Descrição do Procedimento                            0   0.000000
Data de Nascimento                                   0   0.000000
Data do Atendimento                                  0   0.000000
Código do Procedimento                               0   0.000000
Descrição da Unidade                                 0   0.000000
Código da Unidade                                    0   0.000000
Tipo de Unidade                                      0   0.000000
Código do Tipo de Unidade                            0   0.000000
Sexo                                                 0   0.000000
Código do CBO                                        0   0.000000
Desencadeou Internamento                             0   0.000000
Descrição do CBO                                     0   0.000000
Qtde Dispensada Farmácia Curitibana                  0   0.000000
Qtde Prescrita Farmácia Curitibana                   0   0.000000
Encaminhamento para Atendimento Especialista         0   0.000000
Qtde de Medicamento Não Padronizado                  0   0.000000
Solicitação de Exames                                0   0.000000
Energia Elétrica                                     0   0.000000
Municício                                            0   0.000000
Bairro                                               0   0.000000
Nacionalidade                                        0   0.000000
cod_usuario                                          0   0.000000
origem_usuario                                       0   0.000000
residente                                            0   0.000000
cod_profissional                                     0   0.000000

In [13]:
df[['Data do Internamento']].describe()

       Data do Internamento
count                  4448
unique                 4034
top     14/03/2025 03:58:00
freq                      4